# Generated by Django 4.1.3 on 2023-06-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BotanicalApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
